/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PipelinesIndexRouteImport } from './routes/pipelines/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'
import { Route as BuildsIndexRouteImport } from './routes/builds/index'
import { Route as BuildsJobIdRouteImport } from './routes/builds/$jobId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelinesIndexRoute = PipelinesIndexRouteImport.update({
  id: '/pipelines/',
  path: '/pipelines/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildsIndexRoute = BuildsIndexRouteImport.update({
  id: '/builds/',
  path: '/builds/',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildsJobIdRoute = BuildsJobIdRouteImport.update({
  id: '/builds/$jobId',
  path: '/builds/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/pipelines/': typeof PipelinesIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/builds/$jobId': typeof BuildsJobIdRoute
  '/builds/': typeof BuildsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pipelines': typeof PipelinesIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/builds/$jobId': typeof BuildsJobIdRoute
  '/builds': typeof BuildsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/pipelines/': typeof PipelinesIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/builds/$jobId': typeof BuildsJobIdRoute
  '/builds/': typeof BuildsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/pipelines/' | '/projects/' | '/builds/$jobId' | '/builds/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/pipelines' | '/projects' | '/builds/$jobId' | '/builds'
  id: '__root__' | '/' | '/pipelines/' | '/projects/' | '/builds/$jobId' | '/builds/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PipelinesIndexRoute: typeof PipelinesIndexRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  BuildsJobIdRoute: typeof BuildsJobIdRoute
  BuildsIndexRoute: typeof BuildsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipelines/': {
      id: '/pipelines/'
      path: '/pipelines'
      fullPath: '/pipelines/'
      preLoaderRoute: typeof PipelinesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/builds/': {
      id: '/builds/'
      path: '/builds'
      fullPath: '/builds/'
      preLoaderRoute: typeof BuildsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/builds/$jobId': {
      id: '/builds/$jobId'
      path: '/builds/$jobId'
      fullPath: '/builds/$jobId'
      preLoaderRoute: typeof BuildsJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PipelinesIndexRoute: PipelinesIndexRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  BuildsJobIdRoute: BuildsJobIdRoute,
  BuildsIndexRoute: BuildsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
